### ISSUE TITLE
Cannot find module 'React' from 'ReactNativeDefaultInjection.js'

### ISSUE THREAD

**Issue by dadtmt** [exponent/jest-exponent#4]
Hello,

I am trying to use jest with the exponent blank project.

```
import React from 'react'
import renderer from 'react-test-renderer'

import App from './App.js'

it('renders correctly', () => {
  const output = renderer.create(<App />)
  expect(output.toJSON()).toMatchSnapshot()
})
```

```
{
  "name": "my-week",
  "version": "0.0.0",
  "description": "Hello Exponent!",
  "author": null,
  "private": true,
  "main": "main.js",
  "scripts": {
    "test": "jest"
  },
  "jest": {
    "preset": "jest-exponent"
  },
  "dependencies": {
    "@exponent/vector-icons": "~4.0.0",
    "exponent": "^13.1.0",
    "react": "~15.4.0",
    "react-native": "https://github.com/exponent/react-native/archive/sdk-13.0.3.tar.gz"
  },
  "devDependencies": {
    "jest-exponent": "^0.2.0"
  }
}
```
I am getting this error when testing :
```
 Cannot find module 'React' from 'ReactNativeDefaultInjection.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:151:17)
      at Object.<anonymous> (node_modules/react-native/Libraries/Renderer/src/renderers/native/ReactNativeDefaultInjection.js:25:11)

```

**Comment by yurivyatkin** [comment]
@dadtmt it should be fixed now https://github.com/exponent/jest-exponent/commit/309165054b55a81456b67d31a408a603a5840ebc 
Can you confirm this?

**Comment by dadtmt** [comment]
@yurivyatkin yes it is fixed, thank you
